name: deploy

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NodeJS
        uses: actions/setup-node@v1
      - run: npm run build-docs
      - name: deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
          fqdn: willowy.thattomperson.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}